---
- name: Determine if SDKMAN is already installed
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.sdkman"
  register: sdkman_dir
  changed_when: false

- name: Install SDKMAN if not present
  when: not sdkman_dir.stat.exists
  block:
    - name: Download SDKMAN install script
      ansible.builtin.get_url:
        url: "{{ sdkman_repository }}"
        dest: "{{ sdkman_installer_path }}"
        mode: "0755"

    - name: Run SDKMAN install script
      ansible.builtin.shell: "{{ sdkman_installer_path }}"
      args:
        executable: /bin/bash
        creates: "{{ ansible_user_dir }}/.sdkman"

    - name: Make SDKMAN install script executable
      ansible.builtin.file:
        path: "{{ sdkman_installer_path }}"
        mode: "0755"

    - name: Source SDKMAN init script
      ansible.builtin.shell: "source {{ sdkman_init_path }}"
      args:
        executable: /bin/bash
      register: sdkman_source_result
      changed_when: false
      failed_when: sdkman_source_result.rc != 0

- name: Ensure SDKMAN init script exists
  ansible.builtin.stat:
    path: "{{ sdkman_init_path }}"
  register: sdkman_init_script

- name: Fail if SDKMAN init script is missing or empty
  ansible.builtin.fail:
    msg: "SDKMAN init script not found or is empty. Make sure SDKMAN is installed."
  when: not sdkman_init_script.stat.exists or sdkman_init_script.stat.size == 0

- name: Install Java
  ansible.builtin.import_tasks: java.yml

- name: Install Maven
  ansible.builtin.import_tasks: maven.yml
