---
- name: Check if Maven is already installed
  ansible.builtin.command: "mvn --version"
  register: maven_check
  ignore_errors: true
  changed_when: false

- name: Install Maven via SDKMAN
  ansible.builtin.shell: |
    {{ sdkman_init }} && sdk install maven
  when: maven_check.rc != 0
  changed_when: true
