---
- name: Get list of installed VS Code extensions
  ansible.builtin.command: code --list-extensions
  register: vscode_installed_extensions
  changed_when: false
  failed_when: false

- name: Install VS Code extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when: item not in vscode_installed_extensions.stdout_lines
  register: vscode_ext_result
  failed_when:
    - vscode_ext_result.rc != 0
    - "'cannot be downgraded' not in vscode_ext_result.stderr"
  changed_when: true

- name: Create settings.json
  ansible.builtin.copy:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ macos_app_folder }}/Code/User"
    mode: "0644"
