---
- name: Apply macOS Dock settings
  notify: Restart Dock
  block:
    - name: Set Dock minimize effect to '{{ system_dock_minimize_effect }}'
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: string
        value: "{{ system_dock_minimize_effect }}"

    - name: Set Dock icon size to {{ system_dock_icon_size }}
      community.general.osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: float
        value: "{{ system_dock_icon_size }}"

    - name: Hide recent applications from the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: "{{ system_dock_show_recents }}"
