---
- name: Set mouse tracking speed to {{ system_mouse_tracking_speed }}
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.scaling
    type: float
    value: "{{ system_mouse_tracking_speed }}"
