---
- name: Apply macOS trackpad settings
  notify: Restart SystemUIServer
  block:
    - name: Set natural scroll direction
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: "{{ system_trackpad_natural_scroll }}"

    - name: Set trackpad tracking speed to {{ system_trackpad_tracking_speed }}
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.trackpad.scaling
        type: float
        value: "{{ system_trackpad_tracking_speed }}"

    - name: Disable most of trackpad gestures
      community.general.osx_defaults:
        domain: "{{ gesture.domain }}"
        key: "{{ gesture.key }}"
        type: int
        value: 0
      loop:
        - domain: "com.apple.driver.AppleBluetoothMultitouch.trackpad"
          key: "TrackpadTwoFingerDoubleTapGesture"
        - domain: "com.apple.driver.AppleBluetoothMultitouch.trackpad"
          key: "TrackpadPinch"
        - domain: "com.apple.AppleMultitouchTrackpad"
          key: "TrackpadThreeFingerVertSwipeGesture"
        - domain: "com.apple.AppleMultitouchTrackpad"
          key: "TrackpadFourFingerVertSwipeGesture"
        - domain: "com.apple.AppleMultitouchTrackpad"
          key: "TrackpadFourFingerPinchGesture"
      loop_control:
        loop_var: gesture
