---
- name: Initialize empty package lists
  ansible.builtin.set_fact:
    homebrew_packages: []
    homebrew_cask_packages: []

- name: Merge packages from selected profiles
  ansible.builtin.set_fact:
    homebrew_packages: "{{ homebrew_packages + (homebrew_package_profiles[item].packages | default([])) }}"
    homebrew_cask_packages: "{{ homebrew_cask_packages + (homebrew_package_profiles[item].cask_packages | default([])) }}"
  loop: "{{ homebrew_profiles_enabled }}"
  when: homebrew_package_profiles[item] is defined

- name: Deduplicate package lists
  ansible.builtin.set_fact:
    homebrew_packages: "{{ homebrew_packages | unique }}"
    homebrew_cask_packages: "{{ homebrew_cask_packages | unique }}"

- name: Evaluate what needs to be installed
  ansible.builtin.set_fact:
    homebrew_is_installed: "{{ homebrew_check.stat.exists }}"
    homebrew_has_packages: "{{ homebrew_packages | length > 0 }}"
    homebrew_hascask_packages: "{{ homebrew_cask_packages | length > 0 }}"
    homebrew_hasfonts: "{{ homebrew_fonts | default([]) | length > 0 }}"

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present
  register: homebrew_packages_result
  until: homebrew_packages_result is successful
  retries: "{{ default_task_retry }}"
  delay: "{{ default_task_delay }}"
  when: homebrew_is_installed and homebrew_has_packages

- name: Install Homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
  register: homebrew_cask_result
  until: homebrew_cask_result is successful
  retries: "{{ default_task_retry }}"
  delay: "{{ default_task_delay }}"
  when: homebrew_is_installed and homebrew_hascask_packages

- name: Install Homebrew fonts
  community.general.homebrew_cask:
    name: "{{ homebrew_fonts }}"
    state: present
  register: homebrew_fonts_result
  until: homebrew_fonts_result is successful
  retries: "{{ default_task_retry }}"
  delay: "{{ default_task_delay }}"
  when: homebrew_is_installed and homebrew_hasfonts
