---
- name: Installing Homebrew Packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing Homebrew Cask Packages
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Installing fonts via Homebrew
  community.general.homebrew_cask:
    name: "{{ homebrew_fonts }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
