---
- name: Updating Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Upgrading Homebrew Packages
  community.general.homebrew:
    upgrade_all: true
    install_options: force
  register: homebrew_upgrade_result
  until: homebrew_upgrade_result is successful
  when: homebrew_check.stat.exists
