---
- name: Updating Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Upgrading Homebrew Packages
  community.general.homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
