---
- name: Create config to '$HOME/Library/Application\ Support/com.mitchellh.ghostty'
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config"
    dest: "{{ macos_app_folder }}/com.mitchellh.ghostty"
    mode: "0644"
