---
- name: Set up the system
  hosts: local

  pre_tasks:
    - name: Install Ansible Galaxy collections
      ansible.builtin.import_tasks: ../pre_tasks/install_ansible_collections.yaml
      tags:
        - always

    - name: Create various folders
      ansible.builtin.import_tasks: ../pre_tasks/create_folders.yaml
      tags:
        - always

    - name: Ensure Homebrew is installed
      ansible.builtin.import_tasks: ../pre_tasks/ensure_homebrew.yaml
      tags:
        - always

  roles:
    - system
    - homebrew
