---
- name: Ensure nvim is installed
  ansible.builtin.package:
    name: neovim
    state: present

- name: Create the nvim directory in {{ config_dir }}
  ansible.builtin.file:
    path: "{{ config_dir }}/nvim"
    mode: "0755"
    state: directory

- name: Copy files to nvim directory in {{ config_dir }}
  ansible.builtin.copy:
    src: "{{ role_path }}/files"
    dest: "{{ config_dir }}/nvim"
    mode: '0644'

- name: Trigger plugins sync
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
  changed_when: true
